import React from 'react';
import Head from 'next/head';
import resumeasset from '../public/resumeasset.png';
import kazakhstan from '../public/kazakhstan.svg';

import paperplanesvg from "../public/paperplanesvg.svg";
import Image from 'next/image';

const resume = () => {
  return (
    <>
    <Head>
        <title>Noley_Dev : Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" src="../public/favicon32x32a.png" />
        <link rel="icon" type="image/png" sizes="16x16" src="../public/favicon16x16.png" />
      </Head>
      <div className="font-mono border-[16px] border-slate-400 bg-gray-50 h-max mb-0 p-0 flex-row">
<button className="absolute top-5 left-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"><a href="/#">Portfolio</a></button>

           <div className="flex flex-col items-center">        
             <div className="flex flex-row h-[50px] font-bold mt-6">
             <h1 className="mr-8 mt-2 text-[24px]">Nolan</h1><Image src={resumeasset} height={100} width={50} /><h1 className="ml-6 mt-2 text-[24px]">Geiger</h1>
          </div> 
                 
         </div>  
         
      <div className="flex flex-col items-center mt-3">
          
          <div class="grid grid-cols-2 divide-x-4 divide-black-600 divide-dashed mt-4">
            <div className="px-6 text-right"><h1 className="italic">HELLO!</h1><br/>
            <h3>I'm <span className="font-semibold">Nolan</span></h3>
            <h3>Web + Mobile Dev</h3>
            <br/>
            <h3>NYC</h3>
            </div>
            
            <div className="pl-9 text-left"><h1 className='mb-0'>CONTACT</h1>
            <br/>
            <div className="grid grid-cols-2 gap-0 w-36 ">
            <Image src={paperplanesvg} height={50} width={50} className="  p-0 mt-1 ml-0" />
            <h3 className="text-bold mt-2.5">  
            <a href = "mailto: nolan.geiger@gmail.com">nolan.geiger@gmail.com</a></h3>
            </div>
            <h3 className="mt-4">
            #  475-319-9401
            </h3>
          </div>
      </div>
      <hr class="my-2 w-64 h-px bg-gray-600 border-1/2"></hr>
      <div className="m-6"><span className="font-bold">Skills:</span> React, React Native, Javascript, Tailwind, Node, Express and more...</div>
      <hr class="my-2 w-64 h-px bg-gray-600 border-1/2"></hr>

      <div className="mt-0">
      <div className="flex flex-col items-center">
          <div class="grid grid-cols-2 divide-x-4 divide-black-600 divide-dashed">
          
            <div className="px-6 text-right"><h1>PROJECTS</h1><br/>

            <h2 className="font-semibold">KazBnB</h2>
            <h3>Booking site built in React and NextJS</h3>
            <h3>Utilizes Sanity.io for content</h3>
            <h3>Google Maps API for location</h3>
            <br/>
            <h2 className="font-semibold">Notes Mess</h2>
            <h2>Note taking app built in React</h2>
            <h2>Implementing Redux for state management</h2>
            <h2>Fuse.js for fuzzy-matching</h2>
            <br/>
            <h2 className="font-semibold">LingQ Clone</h2>
            <h3>Language learning app: React, Google Translate API</h3>
            <h3>Currently adding MongoDB backend</h3>
            
            </div>
            
            <div className="pl-9 text-left"><h1 className='mb-6'>DEV EDUCATION</h1>
            <div className="my-4">
            <h1 className="italic font-medium mb-1 text-[16px]">Scrimba: Frontend Developer</h1>
            <div className="w-[50%] bg-gray-200 rounded-full dark:bg-gray-700">
    <div className="bg-blue-600 text-xs text-blue-100 text-center p-0.5 leading-none rounded-full w-[100%]"> 100%</div>
  </div><h4 className="text-sm">HTML, CSS, JS + React (70+ hours)</h4></div>
  <div className="my-4">
            <h1 className="italic font-medium mb-1 text-[16px]">GraphQL with React: The Complete Dev's Guide</h1>
            <div className="w-[50%] bg-gray-200 rounded-full dark:bg-gray-700">
    <div className="bg-blue-600 text-xs font-sm text-blue-100 text-center p-0.5 leading-none rounded-full w-[100%]">100%</div>
  </div>
  <h4 className="text-sm">Integrating GraphQL with React (13 hours)</h4>
</div>
<div className="my-4">
  <h1 className="italic font-medium mb-1">The Complete React Native + Hooks Course</h1>
            <div className="w-[50%] bg-gray-200 rounded-full dark:bg-gray-700">
    <div className="bg-blue-600 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-full w-[80%]"> 80%</div>
  </div>
  <h4 className="text-sm">React Native, Context, SDKs, Express, etc. (40+ hours) </h4>
    </div>
    <div className="my-4">
  <h1 className="italic font-medium mb-1">NodeJS - The Complete Guide</h1>
            <div className="w-[50%] bg-gray-200 rounded-full dark:bg-gray-700">
    <div className="bg-blue-600 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-full w-[60%]"> 60%</div>
  </div>
  <h4 className="text-sm">Node, Express, MongoDB + backend development (40 hours) </h4>
  </div>
      
      <h1 className="mt-3">&#8212;See my LinkedIn for more!</h1>
            </div>
      </div>
      </div>
      </div>
      <div className="mt-4">
      <div className="flex flex-col items-center mt-6">
          <div class="grid grid-cols-2 divide-x-4 divide-black-600 divide-dashed mt-6 mb-4">
          
            <div className="px-6 text-right"><h1 className="mb-2">FORMER CAREER</h1>
                    
            <h2 className="font-bold">Teacher</h2>
            <h2 className="font-semibold">English and Social Sciences</h2>
            <h3>NIS School of Chemistry and Biology</h3>
            <h2 className="inline-flex">Petropavl, Republic of Kazakhstan <Image src={kazakhstan} height={40} width={15} className="justify-end"/>
            </h2>
            <h4>2015 - 2021</h4>       
            <br/>
            <h2 className="font-bold">Instructor</h2>
            <h3 className="font-semibold">Philosophy Department</h3>
            <h2>John Jay College of Criminal Justice</h2>
            <h2>New York, NY</h2>
            <h4>2010 - 2015</h4>
            
            
            </div>
            
            <div className="pl-9 text-left"><h1 className='mb-2'>HIGHER EDUCATION</h1>
              
              
              
              <h3><span className="font-semibold">Philosophy, MA</span> &#x2022; SUNY Stony Brook (2010)</h3>
              <h3><span className="font-semibold">Philosophy, BA</span> &#x2022; SUNY Stony Brook (2008)</h3>
              <br/>    
              <h2 className="mb-2">Linguistic Training</h2>
              
              <h2><span className="font-semibold">Ancient Greek </span> &#x2022; CUNY GC (2009)</h2>
              <h2><span className="font-semibold">Latin </span> &#x2022; CUNY GC (2010)</h2>
              
              <hr class="my-2 w-64 h-px bg-gray-600 border-"></hr>
              <h2 className="font-semibold">B1 Level Certificate in Russian (2013)</h2>
              <h1 className="italic">Ukrainian Ministry of Education</h1>
              
              <h2 className="font-semibold">C1 Level Certificate in Russian (2020)</h2>
              <h1 className="italic">Russian Ministry of Education</h1>
            </div>
      </div>
      </div>
      </div>
      </div>
    </div>
    </>
  )
}

export default resume
